Add Audio screen
yili288/readease pull request #5
Opened 2023-10-24 22:27 UTC by Peteredwardj

Resolves [UI for text-to-speech screen](https://trello.com/c/pc18nY0Y/14-ui-for-text-to-speech-screen-2) 

- Default main screen to audio screen temporarily, since we don't have the text screen yet to navigate from 
-  Loads audio image from a URL
-  Scrollable audio slider
-  Functioning buttons to scroll through the slider by 5%
-  Functioning button to change  playback speed (defaults to 1x)

Notes: 
- Will have to add the load audio, text title and image URL dynamically in the future
- Important file to look at:  src/screens/AudioScreen.tsx

**Demo**
![RocketSim_Recording_iPhone_SE_(3rd_generation)_2023-10-24_18 17 14](https://github.com/yili288/readease/assets/51882829/590a6597-7b67-4a20-8de5-16d19b5ae416)

2023-10-24 22:28 UTC, Peteredwardj commented on src/screens/AudioScreen.tsx
The only file to review, everything else are just dependencies

2023-10-24 22:30 UTC, Peteredwardj commented on src/navigation/Navigator.tsx
> +      <Stack.Screen name="AudioScreen" component={AudioScreen} />
For now default to this view, since we have no text page to navigate from

2023-10-24 22:30 UTC, Peteredwardj commented on src/screens/AudioScreen.tsx
> +    const nextSpeedIndex = speedIndex === maxSpeedIndex ? 0 : speedIndex + 1; //at 2, we go back to 0
*2x

2023-10-24 22:55 UTC, yili288 commented on src/screens/AudioScreen.tsx
thanks!

2023-10-24 22:59 UTC, Peteredwardj commented on src/screens/AudioScreen.tsx
> +          {((sliderValue / audioLength) * 100).toFixed(0)}%
% of how far we're along in the playback

2023-10-24 23:01 UTC, Peteredwardj commented on src/screens/AudioScreen.tsx
note that this versions is outdated, pushed some commits after

2023-10-24 23:06 UTC, Peteredwardj commented on src/screens/AudioScreen.tsx
Only file to review

2023-10-25 22:57 UTC, yili288 requested changes
looks good, I can integrate the audio player into this UI in another PR! I just merged Jiachang's code, can you resolve the conflicts or rebase main?

2023-10-27 17:01 UTC, yili288 approved these changes

2023-10-27 20:22 UTC, merged